version: 2
jobs:
  build:
    machine: true
      
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: go get -d
      
      - run:
          name: Prepare background server's credentials
          command: |
            echo "AUTH0_DOMAIN=$domain" >> .env
            echo "AUTH0_AUDIENCE=$audience" >> .env
      
      - run:
          name: Execute background server
          command: go run main.go
          background: true
      
      - run: sleep 10
          
      - run:
          name: update node
          comand:  |
            sudo apt-get update
            sudo apt-get install nodejs
            
      - run:
          name: Prepare and execute tests
          command: | 
            cd test
            node -v
            npm install && npm test
          
