version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/node:9.4.0
      
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name: install dependencies
          command: go get -d
      
      - run: 
          name: set background server credentials
          command: |
            echo "AUTH0_DOMAIN=$domain" >> .env
            echo "AUTH0_AUDIENCE=$audience" >> .env
      
      - run: 
          name: background server
          command: go run main.go
          background: true
      
